import {test,expect} from '@playwright/test';
test('public demo: render, Markdown persistence, three levels, media previews and no backend',async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
 const backend:string[]=[];page.on('request',r=>{if(new URL(r.url()).pathname.startsWith('/api/'))backend.push(r.url());});
 await page.goto('./');
 await expect(page.getByText('公开示例 · 修改仅存在当前浏览器 · 未连接 Agent')).toBeVisible();
 await expect(page.locator('.canvas-card').first()).toBeVisible();
 await expect(page.getByRole('img',{name:'Mermaid 图表',exact:true})).toBeVisible();
 await page.screenshot({path:'test-results/demo-overview.png',fullPage:true});
 const basics=page.locator('[data-id="showcase-basics-place"]');
 await basics.getByRole('button',{name:'编辑01 / 卡片是工作的基本单元正文'}).click();
 await basics.getByRole('textbox',{name:'01 / 卡片是工作的基本单元正文',exact:true}).fill('## 浏览器保存验收\n\n- [x] 已完成\n\n**Markdown 持久化**');
 await page.getByRole('button',{name:'批注列表',exact:true}).click();
 await expect(basics.getByRole('heading',{name:'浏览器保存验收'})).toBeVisible();
 await page.reload();await expect(page.getByRole('heading',{name:'浏览器保存验收'})).toBeVisible();
 await page.getByRole('button',{name:'进入 03 / 功能地图 · 点此进入',exact:true}).click();
 await page.getByRole('button',{name:'进入 持久化共创',exact:true}).click();
 await expect(page.getByText('使用上方「主画布」或面包屑返回。',{exact:false})).toBeVisible();
 await page.getByRole('navigation',{name:'画布路径'}).getByRole('button',{name:'主画布',exact:true}).click();
 await page.getByRole('link',{name:'示例图片',exact:true}).click();
 await expect(page.getByRole('img',{name:'board.png',exact:true})).toBeVisible();
 await page.getByRole('button',{name:'关闭文件预览'}).click();
 await page.getByRole('link',{name:'示例视频',exact:true}).click();
 await expect.poll(()=>page.locator('video').evaluate((v:HTMLVideoElement)=>v.duration)).toBeGreaterThan(4);
 await page.getByRole('button',{name:'关闭文件预览'}).click();
 await page.getByRole('link',{name:'Markdown 文件',exact:true}).click();
 await expect(page.getByRole('heading',{name:'从想法到共同产出',exact:true})).toBeVisible();
 await page.getByRole('button',{name:'关闭文件预览'}).click();
 await page.getByRole('button',{name:'连接 Agent',exact:true}).click();
 await expect(page.getByText('连接 Agent · 本地版能力', {exact:true})).toBeVisible();
 expect(backend).toEqual([]);expect(errors).toEqual([]);
});
